version: "3.9"
services:
  web:
    container_name: web3
    hostname: web
    build:
      context: ./djangogram
      dockerfile: Dockerfile
    command: gunicorn djangogram.wsgi:application --workers 5 --timeout=600 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/mnt/data/djangogram/static
      - media_volume:/mnt/data/djangogram/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres3
    hostname: postgres
    image: "postgres:15.3"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  nginx:
    container_name: nginx3
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/mnt/data/djangogram/static
      - media_volume:/mnt/data/djangogram/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: